const championData = {
    Aatrox:      { traits: ['Juggernaut', 'Heavyweight', 'Mighty Mech'] },
    Ahri:        { traits: ['Sorcerer', 'Star Guardian'] },
    Akali:       { traits: ['Executioner', 'Supreme Cells'] },
    Ashe:        { traits: ['Sniper', 'Crystal Gambit'] },
    Braum:       { traits: ['Bastion', 'Luchador', 'The Champ'] },
    Caitlyn:     { traits: ['Sniper', 'Battle Academia'] },
    Darius:      { traits: ['Executioner', 'Supreme Cells'] },
    DrMundo:     { traits: ['Juggernaut', 'Luchador'] },
    Ezreal:      { traits: ['Prodigy', 'Battle Academia'] },
    Gangplank:   { traits: ['Duelist', 'Mighty Mech'] },
    Garen:       { traits: ['Bastion', 'Battle Academia'] },
    Gnar:        { traits: ['Sniper', 'Luchador'] },
    Gwen:        { traits: ['Sorcerer', 'Soul Fighter'] },
    Janna:       { traits: ['Strategist', 'Protector', 'Crystal Gambit'] },
    JarvanIV:    { traits: ['Strategist', 'Mighty Mech'] },
    Jayce:       { traits: ['Heavyweight', 'Battle Academia'] },
    Jhin:        { traits: ['Sniper', 'Wraith'] },
    Jinx:        { traits: ['Sniper', 'Star Guardian'] },
    KSante:      { traits: ['Protector', 'Wraith'] },
    Kaisa:       { traits: ['Duelist', 'Supreme Cells'] },
    Kalista:     { traits: ['Executioner', 'Soul Fighter'] },
    Karma:       { traits: ['Sorcerer', 'Mighty Mech'] },
    Katarina:    { traits: ['Executioner', 'Battle Academia'] },
    Kayle:       { traits: ['Duelist', 'Wraith'] },
    Kennen:      { traits: ['Sorcerer', 'Supreme Cells', 'Protector'] },
    Kobuko:      { traits: ['Heavyweight', 'Mentor'] },
    KogMaw:      { traits: ['No Class', 'Monster Trainer'] },
    LeeSin:      { traits: ['No Class','Stance Master'] },
    Leona:       { traits: ['Bastion', 'Battle Academia'] },
    Lucian:      { traits: ['Sorcerer', 'Mighty Mech'] },
    Lulu:        { traits: ['No Class', 'Monster Trainer'] },
    Lux:         { traits: ['Sorcerer', 'Soul Fighter'] },
    Malphite:    { traits: ['Protector', 'The Crew'] },
    Malzahar:    { traits: ['Prodigy', 'Wraith'] },
    Naafiri:     { traits: ['Juggernaut', 'Soul Fighter'] },
    Neeko:       { traits: ['Protector', 'Star Guardian'] },
    Poppy:       { traits: ['Heavyweight', 'Star Guardian'] },
    Rakan:       { traits: ['Protector', 'Battle Academia'] },
    Rammus:      { traits: ['No Class', 'Monster Trainer'] },
    Rell:        { traits: ['Bastion', 'Star Guardian'] },
    Ryze:        { traits: ['Strategist', 'Executioner', 'Mentor'] },
    Samira:      { traits: ['Edgelord', 'Soul Fighter'] },
    Senna:       { traits: ['Executioner', 'Mighty Mech'] },
    Seraphine:   { traits: ['Prodigy', 'Star Guardian'] },
    Sett:        { traits: ['Juggernaut', 'Soul Fighter'] },
    Shen:        { traits: ['Bastion', 'Edgelord', 'The Crew'] },
    Sivir:       { traits: ['Sniper', 'The Crew'] },
    Smolder:     { traits: ['No Class', 'Monster Trainer'] },
    Swain:       { traits: ['Sorcerer', 'Crystal Gambit', 'Bastion'] },
    Syndra:      { traits: ['Prodigy', 'Crystal Gambit', 'Star Guardian'] },
    TwistedFate: { traits: ['No Class', 'The Crew', 'Rogue Captain'] },
    Udyr:        { traits: ['Juggernaut', 'Mentor', 'Duelist'] },
    Varus:       { traits: ['Sniper', 'Wraith'] },
    Vi:          { traits: ['Juggernaut', 'Crystal Gambit'] },
    Viego:       { traits: ['Duelist', 'Soul Fighter'] },
    Volibear:    { traits: ['Edgelord', 'Luchador'] },
    Xayah:       { traits: ['Edgelord', 'Star Guardian'] },
    XinZhao:     { traits: ['Bastion', 'Soul Fighter'] },
    Yasuo:       { traits: ['Edgelord', 'Mentor'] },
    Yone:        { traits: ['Edgelord', 'Mighty Mech'] },
    Yuumi:       { traits: ['Prodigy', 'Battle Academia'] },
    Zac:         { traits: ['Heavyweight', 'Wraith'] },
    Ziggs:       { traits: ['Strategist', 'The Crew'] },
    Zyra:        { traits: ['No Class', 'Rosemother', 'Crystal Gambit'] },
  };
  

export default championData;
