// Champion data with Set 15 traits from TFTactics.gg
const championData = {
  'Aatrox': { traits: ['Bastion', 'The Champ'] },
  'Ahri': { traits: ['Sorcerer', 'Star Guardian'] },
  'Akali': { traits: ['Executioner', 'Star Guardian'] },
  'Ashe': { traits: ['Sniper', 'Crystal Gambit'] },
  'Braum': { traits: ['Bastion', 'Crystal Gambit'] },
  'Caitlyn': { traits: ['Sniper', 'Battle Academia'] },
  'Darius': { traits: ['Executioner', 'The Champ'] },
  'DrMundo': { traits: ['Juggernaut', 'The Crew'] },
  'Ezreal': { traits: ['Sniper', 'Battle Academia'] },
  'Gangplank': { traits: ['Duelist', 'The Crew'] },
  'Garen': { traits: ['Bastion', 'Battle Academia'] },
  'Gnar': { traits: ['Juggernaut', 'Monster Trainer'] },
  'Gwen': { traits: ['Executioner', 'Star Guardian'] },
  'Janna': { traits: ['Sorcerer', 'The Crew'] },
  'JarvanIV': { traits: ['Bastion', 'Battle Academia'] },
  'Jayce': { traits: ['Juggernaut', 'Battle Academia'] },
  'Jhin': { traits: ['Sniper', 'The Champ'] },
  'Jinx': { traits: ['Sniper', 'The Crew'] },
  'KSante': { traits: ['Bastion', 'The Champ'] },
  'Kaisa': { traits: ['Executioner', 'Supreme Cells'] },
  'Kalista': { traits: ['Executioner', 'Wraith'] },
  'Karma': { traits: ['Sorcerer', 'Star Guardian'] },
  'Katarina': { traits: ['Executioner', 'The Champ'] },
  'Kayle': { traits: ['Executioner', 'Battle Academia'] },
  'Kennen': { traits: ['Sorcerer', 'Star Guardian'] },
  'Kobuko': { traits: ['Bastion', 'Luchador'] },
  'KogMaw': { traits: ['Sniper', 'Supreme Cells'] },
  'LeeSin': { traits: ['Duelist', 'Luchador'] },
  'Leona': { traits: ['Bastion', 'Battle Academia'] },
  'Lucian': { traits: ['Sniper', 'Battle Academia'] },
  'Lulu': { traits: ['Sorcerer', 'Star Guardian'] },
  'Lux': { traits: ['Sorcerer', 'Battle Academia'] },
  'Malphite': { traits: ['Bastion', 'Monster Trainer'] },
  'Malzahar': { traits: ['Sorcerer', 'Supreme Cells'] },
  'Naafiri': { traits: ['Executioner', 'Supreme Cells'] },
  'Neeko': { traits: ['Sorcerer', 'Star Guardian'] },
  'Poppy': { traits: ['Bastion', 'Star Guardian'] },
  'Rakan': { traits: ['Bastion', 'Star Guardian'] },
  'Rammus': { traits: ['Bastion', 'Monster Trainer'] },
  'Rell': { traits: ['Bastion', 'The Champ'] },
  'Ryze': { traits: ['Sorcerer', 'The Crew'] },
  'Samira': { traits: ['Executioner', 'The Crew'] },
  'Senna': { traits: ['Sniper', 'Wraith'] },
  'Seraphine': { traits: ['Sorcerer', 'Star Guardian'] },
  'Sett': { traits: ['Bastion', 'Luchador'] },
  'Shen': { traits: ['Bastion', 'Star Guardian'] },
  'Sivir': { traits: ['Sniper', 'The Champ'] },
  'Smolder': { traits: ['Sniper', 'Monster Trainer'] },
  'Swain': { traits: ['Sorcerer', 'The Champ'] },
  'Syndra': { traits: ['Sorcerer', 'Star Guardian'] },
  'TwistedFate': { traits: ['Sorcerer', 'The Crew'] },
  'Udyr': { traits: ['Juggernaut', 'Luchador'] },
  'Varus': { traits: ['Sniper', 'Star Guardian'] },
  'Vi': { traits: ['Bastion', 'Battle Academia'] },
  'Viego': { traits: ['Executioner', 'Wraith'] },
  'Volibear': { traits: ['Juggernaut', 'Monster Trainer'] },
  'Xayah': { traits: ['Executioner', 'Star Guardian'] },
  'XinZhao': { traits: ['Duelist', 'Battle Academia'] },
  'Yasuo': { traits: ['Duelist', 'The Champ'] },
  'Yone': { traits: ['Duelist', 'The Champ'] },
  'Yuumi': { traits: ['Sorcerer', 'Star Guardian'] },
  'Zac': { traits: ['Juggernaut', 'The Crew'] },
  'Ziggs': { traits: ['Sorcerer', 'The Crew'] },
  'Zyra': { traits: ['Sorcerer', 'Star Guardian'] }
};

export default championData;
