const championData = {
    Aatrox:      { classes: ['Juggernaut', 'Heavyweight'], origins: ['Mighty Mech'] },
    Ahri:        { classes: ['Sorcerer'], origins: ['Star Guardian'] },
    Akali:       { classes: ['Executioner'], origins: ['Supreme Cells'] },
    Ashe:        { classes: ['Sniper'], origins: ['Crystal Gambit'] },
    Braum:       { classes: ['Bastion'], origins: ['Luchador', 'The Champ'] },
    Caitlyn:     { classes: ['Sniper'], origins: ['Battle Academia'] },
    Darius:      { classes: ['Executioner'], origins: ['Supreme Cells'] },
    DrMundo:     { classes: ['Juggernaut'], origins: ['Luchador'] },
    Ezreal:      { classes: ['Prodigy'], origins: ['Battle Academia'] },
    Gangplank:   { classes: ['Duelist'], origins: ['Mighty Mech'] },
    Garen:       { classes: ['Bastion'], origins: ['Battle Academia'] },
    Gnar:        { classes: ['Sniper'], origins: ['Luchador'] },
    Gwen:        { classes: ['Sorcerer'], origins: ['Soul Fighter'] },
    Janna:       { classes: ['Strategist', 'Protector'], origins: ['Crystal Gambit'] },
    JarvanIV:    { classes: ['Strategist'], origins: ['Mighty Mech'] },
    Jayce:       { classes: ['Heavyweight'], origins: ['Battle Academia'] },
    Jhin:        { classes: ['Sniper'], origins: ['Wraith'] },
    Jinx:        { classes: ['Sniper'], origins: ['Star Guardian'] },
    KSante:      { classes: ['Protector'], origins: ['Wraith'] },
    Kaisa:       { classes: ['Duelist'], origins: ['Supreme Cells'] },
    Kalista:     { classes: ['Executioner'], origins: ['Soul Fighter'] },
    Karma:       { classes: ['Sorcerer'], origins: ['Mighty Mech'] },
    Katarina:    { classes: ['Executioner'], origins: ['Battle Academia'] },
    Kayle:       { classes: ['Duelist'], origins: ['Wraith'] },
    Kennen:      { classes: ['Sorcerer', 'Protector'], origins: ['Supreme Cells'] },
    Kobuko:      { classes: ['Heavyweight'], origins: ['Mentor'] },
    KogMaw:      { classes: [], origins: ['Monster Trainer'] },
    LeeSin:      { classes: [], origins: ['Stance Master'] },
    Leona:       { classes: ['Bastion'], origins: ['Battle Academia'] },
    Lucian:      { classes: ['Sorcerer'], origins: ['Mighty Mech'] },
    Lulu:        { classes: [], origins: ['Monster Trainer'] },
    Lux:         { classes: ['Sorcerer'], origins: ['Soul Fighter'] },
    Malphite:    { classes: ['Protector'], origins: ['The Crew'] },
    Malzahar:    { classes: ['Prodigy'], origins: ['Wraith'] },
    Naafiri:     { classes: ['Juggernaut'], origins: ['Soul Fighter'] },
    Neeko:       { classes: ['Protector'], origins: ['Star Guardian'] },
    Poppy:       { classes: ['Heavyweight'], origins: ['Star Guardian'] },
    Rakan:       { classes: ['Protector'], origins: ['Battle Academia'] },
    Rammus:      { classes: [], origins: ['Monster Trainer'] },
    Rell:        { classes: ['Bastion'], origins: ['Star Guardian'] },
    Ryze:        { classes: ['Strategist', 'Executioner'], origins: ['Mentor'] },
    Samira:      { classes: ['Edgelord'], origins: ['Soul Fighter'] },
    Senna:       { classes: ['Executioner'], origins: ['Mighty Mech'] },
    Seraphine:   { classes: ['Prodigy'], origins: ['Star Guardian'] },
    Sett:        { classes: ['Juggernaut'], origins: ['Soul Fighter'] },
    Shen:        { classes: ['Bastion', 'Edgelord'], origins: ['The Crew'] },
    Sivir:       { classes: ['Sniper'], origins: ['The Crew'] },
    Smolder:     { classes: [], origins: ['Monster Trainer'] },
    Swain:       { classes: ['Sorcerer', 'Bastion'], origins: ['Crystal Gambit'] },
    Syndra:      { classes: ['Sorcerer'], origins: ['Crystal Gambit', 'Star Guardian'] },
    TwistedFate: { classes: [], origins: ['The Crew', 'Rogue Captain'] },
    Udyr:        { classes: ['Juggernaut', 'Duelist'], origins: ['Mentor'] },
    Varus:       { classes: ['Sniper'], origins: ['Wraith'] },
    Vi:          { classes: ['Juggernaut'], origins: ['Crystal Gambit'] },
    Viego:       { classes: ['Duelist'], origins: ['Soul Fighter'] },
    Volibear:    { classes: ['Edgelord'], origins: ['Luchador'] },
    Xayah:       { classes: ['Edgelord'], origins: ['Star Guardian'] },
    XinZhao:     { classes: ['Bastion'], origins: ['Soul Fighter'] },
    Yasuo:       { classes: ['Edgelord'], origins: ['Mentor'] },
    Yone:        { classes: ['Edgelord'], origins: ['Mighty Mech'] },
    Yuumi:       { classes: ['Prodigy'], origins: ['Battle Academia'] },
    Zac:         { classes: ['Heavyweight'], origins: ['Wraith'] },
    Ziggs:       { classes: ['Strategist'], origins: ['The Crew'] },
    Zyra:        { classes: [], origins: ['Rosemother', 'Crystal Gambit'] },
  };
  

export default championData;
